spring:
  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.maptsdpqsyuvmmqhnofv
    password: ZSGhQwZBUl1EQpCV
    hikari:
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

supabase:
  url: https://maptsdpqsyuvmmqhnofv.supabase.co
  anon-key: sb_publishable_uNq2BzI3BE-UdwKLIYx7rg_PDF1uUST

apiperu:
  url: https://apiperu.dev/api/dni
  token: 18155|w1r35b4TmjwlS8M8K8ephJs2TISPlIjyRcXGxRteb0bf321a

groq:
  api-key: ${GROQ_API_KEY}

